### ISSUE TITLE
Display the tags and categories attached in the article in the sidebar.

### ISSUE THREAD

**Issue by zabio3** [alanorth/hugo-theme-bootstrap4-blog#104]
Thank you for creating a very easy-to-use theme. I am using this theme:D

I thought that it would be more convenient if you use it and have the following functions.

I want to display the tags and categories attached in the article in the sidebar.

**Comment by alanorth** [comment]
Thanks for the comment, @zabio3. When I designed the theme I was going for something more traditional and close to the original [Bootstrap Blog theme](https://v4-alpha.getbootstrap.com/examples/blog/).
