### ISSUE TITLE
html tag <a>https

### ISSUE THREAD

**Issue by Alonsovau** [alanorth/hugo-theme-bootstrap4-blog#106]
Hello, it's a good hugo theme.
Today, i found the tags and categories links do not work.
It does not work on Chrome 72 and Edge on Windows10 1803, but works on IE and firefox 64.
I add {{"/"}}, it works.
```html
<a class="badge badge-primary" href="{{ "/tags/" | relLangURL }}{{ . | urlize }}{{"/"}}">{{ . }}</a>
```
Thank you for this theme!

**Comment by alanorth** [comment]
Thanks for the report. The tags and categories work for me on Chromium 72 on Linux. I don't have access to Windows, but could you please try here on my blog: [picturingjordan.com](https://picturingjordan.com/).

**Comment by Alonsovau** [comment]
Thanks for your reply. It works well on Chrome 72 on Windows 10 and macOS.
I found "https" will be "http" when I use my company's network. If I switch the network, it works well.
After adding "/", it always works.

**Comment by alanorth** [comment]
> Thanks for your reply. It works well on Chrome 72 on Windows 10 and macOS. I found "https" will be "http" when I use my company's network. If I switch the network, it works well.
After adding "/", it always works.

Sorry, I don't understand what the problem is now. It sounds like a configuration issue in your site to me. :thinking:

**Comment by Alonsovau** [comment]
It's my network prolem.
Tnanks a lot! 👍
