### ISSUE TITLE
Css Entire page shifts out of alignment.

### ISSUE THREAD

**Issue by Jieiku** [alanorth/hugo-theme-bootstrap4-blog#121]
So normally on your main home page you will have enough items that there is a scrollbar visible on the right side. If you make a new post that is short enough to not show the scrollbar, then the entire page shifts left to right. It is very noticeable and makes the site look inconsistent.

One workaround is to make sure that every single post is a long enough post that it always shows the scrollbar, however this would be a good one to fix if possible.

The entire page shifts as a result of the scrollbar hiding on shorter posts.

![image](https://user-images.githubusercontent.com/106644/72966661-4cab0b00-3d74-11ea-92d4-28fc76b3010b.png)

**Comment by Jieiku** [comment]
OH! Also I have the "About" section and "Links" section hidden, showing only the "Recent Posts" Section. So quite possibly all I need to do is have more items in that right column and there will Always be a scrollbar. So maybe this is only an issue because my site is new and once I have more content on that smaller right column the scrollbar will always be visible.

If you agree you can just close this. Eventually I will have a lot more content filling the page so I am not that worried.

**Comment by alanorth** [comment]
Yeah I'm not a CSS expert so if there is a bug there I wouldn't know how to fix it. Seems pretty minor to me, and I don't notice anything on my personal blog. Closing this.
