### ISSUE TITLE
theme/layhouts/_default/list.html

### ISSUE THREAD

**Issue by Jieiku** [alanorth/hugo-theme-bootstrap4-blog#122]
These two lines are both for GooglePlus? GooglePlus is gone with the wind:

```
  {{- with .Site.Social.GooglePlus }}
  "publisher": "{{ printf "%s" . }}",
```

**Comment by alanorth** [comment]
Yep, it looks like those were missed when someone sent a pull request to remove the Google Plus sharing icon (#108). Thanks, I've removed it now (32af2194912ae86f12779d34e36fa4a6c010d06b).
