### ISSUE TITLE
Support for a custom navbar

### ISSUE THREAD

**Issue by ejsmit** [alanorth/hugo-theme-bootstrap4-blog#13]
I would like the ability to have more control over the contents of the navbar.  The default behaviour is to link all pages that are not posts, but I have too many static pages, and only want  a small subset of them in my navbar.

The default behaviour should be backward compatible, but with a params option that can be uncommented/enabled to display a custom hugo menu instead.  This will allow me to add `menu = "navbar"` to only the specific pages that I want in the navbar.

I would be happy to create a pull request if you think this is a sensible change.

Rassie

**Comment by alanorth** [comment]
You're right, the default navbar behavior is very limited and only fits a basic use case. I'd be happy if you submitted a pull request with an optional, configurable navbar. 👏

**Comment by alanorth** [comment]
Closed in #15.
