### ISSUE TITLE
How to add background image to the site?

### ISSUE THREAD

**Issue by ipstone** [alanorth/hugo-theme-bootstrap4-blog#132]
Hello, thanks for this theme, it's super useful!

My question is how to add a background image (transparent) to the hugo site? Is there someplace where we can modify to add some css code such as:

```
body {
 background-image: url("paper.png");
 background-color: #cccccc;
}
```
thanks for your help/suggestions in advance!

-- ipstone

**Comment by alanorth** [comment]
Dear @ipstone, you can add custom code to the `<head>` by creating a `layouts/partials/head-custom.html` file in your blog and the theme will include it when it builds. See #17 where this was added. Cheers!
