### ISSUE TITLE
Font awesome icon availability

### ISSUE THREAD

**Issue by boydkelly** [alanorth/hugo-theme-bootstrap4-blog#134]
Hi, Great theme.   My only issue right now is font awesome.  I want to replace "share" with an icon in the same family as the current facebook, linkedin, and twitter icons.   I thougt it would be as simple as inserting something like 
`<span class="fas fa-share"></span>
`
But I can't get anything to work.   I just get a pulsating exclamation mark.   I am using an svg image as a work around but I would also like to insert an rss icon as well.   Can you point me in the right direction.

Once I get finished I may send you a pull request for a couple of i18n things.  Thanks.
(https://titro.pro)

**Comment by alanorth** [comment]
Hey! Check the source/scss/fontawesome.scss. I'm only importing a subset of
the Font Awesome icons in order to save space. I can add a few more if you
tell me which ones you want.

For i18n that's great. Please send.

**Comment by boydkelly** [comment]
Thanks!  ok I was thinking it was with scss.  In the meantime I have a solution, but the two icons i need are pretty generic (for rss and sharing):  <i class="fas fa-rss"></i> and <i class="fas fa-share-alt"></i> Cheers!

**Comment by alanorth** [comment]
Oops, I was on mobile when I responded to that and I forgot that I switched to using SVG. Now the icons are selectively imported in the `source/js/fontawesome.js` instead. Do you want these two icons?

- [share-alt](https://fontawesome.com/icons/share-alt?style=solid)
- [rss](https://fontawesome.com/icons/rss?style=solid)

I can add them for you.
