### ISSUE TITLE
Project zip file being detected as virus

### ISSUE THREAD

**Issue by prateeksingla** [alanorth/hugo-theme-bootstrap4-blog#135]
I am unable to use this theme as I am getting virus warning as below:
![image](https://user-images.githubusercontent.com/1451694/82881588-81ff7980-9f5d-11ea-8653-f3821951c6f4.png)

**Comment by alanorth** [comment]
Whaaaaat? LOL! Umm, I only use Linux so I have no idea what could cause that. I see you're trying to use the master zip file. Maybe try [the latest release (v1.5.0)](https://github.com/alanorth/hugo-theme-bootstrap4-blog/releases/tag/v1.5.0)?

Alternatively, you could try to use `git clone` if you have the git client installed. Sorry, I don't know anything about Windows.

**Comment by fte378** [comment]
@prateeksingla  The Anti-Virus program possibly gives you the option to ignore the warning. Click on the "Actions" button to see if this is possible.
The mentioned file for sure does not contain a Windows trojan program (after all - its only a text file).
