### ISSUE TITLE
Can't tip you with BAT tokens :)

### ISSUE THREAD

**Issue by fte378** [alanorth/hugo-theme-bootstrap4-blog#136]
I think you still have to verify your wallet.

**Comment by alanorth** [comment]
@fte378 you mean the Brave cryptocurrency thing? I don't use it. Why do you want to tip me? :yum:

**Comment by fte378** [comment]
Why not?   You must have established a channel there - my browser shows me the tip symbol in your messages on Github.

**Comment by alanorth** [comment]
Hmm I never used Brave. I'm diehard Firefox! Maybe Brave is doing something wrong or sneaky by showing the icon? What can you do with the tokens? :P

**Comment by fte378** [comment]
Ah yes. It seems to be a way to increase the user base for the tokens. It's displayed in every github message.
I distribute the tokens to the projects I like. A cheap way to contribute something ;-)

So the issue can be closed I guess.
