### ISSUE TITLE
custom head not working

### ISSUE THREAD

**Issue by damnms** [alanorth/hugo-theme-bootstrap4-blog#137]
i tried like mentioned in https://github.com/alanorth/hugo-theme-bootstrap4-blog/pull/17 but that was not working

i created /home/me/Downloads/website/layouts/partial/head-custom.html with content "TEST"
so i would expect somewhere a "TEST" in the source, but there was nothing.

my root of the website is for testing currently at /home/me/Downloads/website

**Comment by damnms** [comment]
should be in partials, not partial - maybe the documentation should be updated

**Comment by alanorth** [comment]
There's no documentation per se, but the README.md says this:

```
Allow addition of custom <head> code in site's layouts/partials/head-custom.html (see #17)
```

Linked pull request #17 is a user's PR adding the custom head feature and I guess he made a typo there.
