### ISSUE TITLE
Did not add PrismJS very well

### ISSUE THREAD

**Issue by outbegin** [alanorth/hugo-theme-bootstrap4-blog#142]
Did not add PrismJS very well
Integration of PrismJS resulted in color conflict

**Comment by alanorth** [comment]
Hi @outbegin. I don't use PrismJS in the theme. How are you trying to add it?

**Comment by outbegin** [comment]
Thank you for your reply.
Prism is a lightweight, extensible syntax highlighter. His website is https://prismjs.com.
![image](https://user-images.githubusercontent.com/60064240/99261128-416f2180-2857-11eb-9514-ef37a56168be.png)
![image](https://user-images.githubusercontent.com/60064240/99263474-38cc1a80-285a-11eb-9352-fd61e5de181f.png)

The final effect should be like this:
![image](https://user-images.githubusercontent.com/60064240/99261976-5dbf8e00-2858-11eb-9f6b-87bcf48f2b01.png)

**Comment by outbegin** [comment]
I looked at the official documentation and found an alternative.
https://gohugo.io/getting-started/configuration-markup#highlight

**Comment by alanorth** [comment]
That's good, @outbegin. I am glad you have a solution. Closing now...
