### ISSUE TITLE
dropdown menu does not work

### ISSUE THREAD

**Issue by araneta** [alanorth/hugo-theme-bootstrap4-blog#144]
i tried to add dropdown menu using this code:

`<nav class="nav blog-nav">
			<div class="collapse navbar-collapse">
				<ul class="navbar-nav mr-auto">
					{{ range .Site.Menus.navbar }}
					  <li class="nav-item dropdown">
						{{ if .HasChildren }}
						  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ .Name }} <span class="caret"></span></a>
						<div class="dropdown-menu">
						  {{ range .Children }}
							<a class="dropdown-item" href="{{ .URL }}">{{ .Name }}</a>
						  {{ end }}
						</div>
						{{ else }}
						<a href="{{ .URL }}">{{ .Name }}</a>
						{{ end  }}
					  </li>
				 {{ end }}
				</ul>
			</div>
        </nav>`

but it does not work

**Comment by alanorth** [comment]
@araneta That's probably a JavaScript issue. I don't use drop down menus in this project so I am not sure. You should try to add the required JavaScript libraries. Check the [Bootstrap v4.5 docs](https://getbootstrap.com/docs/4.5/components/navbar/).
