### ISSUE TITLE
Why does the build version of this theme doesn't look like the live one? 

### ISSUE THREAD

**Issue by JAQuent** [alanorth/hugo-theme-bootstrap4-blog#149]
Hey, 

I've an issue that I created a website with this theme (see [https://jaquent.github.io/](https://jaquent.github.io/)), which is rendered for me like

![image](https://user-images.githubusercontent.com/17894303/216906550-f0124e50-7bec-4128-89d5-0630be1464bd.png)

but the live version that I create with R blogdown looks like this

![image](https://user-images.githubusercontent.com/17894303/216906795-d8f8741d-3c1b-4076-8cda-8ab5caa6625e.png)

There are more differences than just this. Can you tell what am I doing wrong? The theme otherwise perfectly for me.

**Comment by alanorth** [comment]
Oh I just looked at this an it seems you figured it out. Cheers. :)
