### ISSUE TITLE
Support right-to-left languages like Arabic

### ISSUE THREAD

**Issue by alanorth** [alanorth/hugo-theme-bootstrap4-blog#16]
It would be amazing if the theme supported right-to-left (RTL) languages like Arabic. I think I could use something like [bi-app-sass](https://github.com/anasnakawa/bi-app-sass) or [css-flip](https://github.com/twitter/css-flip) but have zero experience with RTL CSS.

A quick, dirty hack with some gibberish + Google Translated Arabic text looks *slightly* promising (some block elements are flipped to the other side):

![screen shot 2016-11-20 at 11 28 29-fs8](https://cloud.githubusercontent.com/assets/191754/20461914/b3244a4a-af15-11e6-9f74-70a879a49d75.png)

Sorry for the horrible Arabic. :)

**Comment by alanorth** [comment]
I made great progress on the RTL issue last week. It was very easy once I discovered [rtlcss](https://rtlcss.com/) and integrated it into my npm build tasks. Once I've generated the CSS it is trivial to conditionally include it in the theme using hugo's golang template functions, ie `if eq .Lang "ar"`. After that we only need to conditionally set `dir=rtl` on the HTML element and now it's mostly finished. The Arabic translations of UI strings have also been drastically improved by a native Arabic speaker.

Here is a draft post I have in Arabic:

![Screenshot_2019-04-22 النظافة من الايمان-fs8](https://user-images.githubusercontent.com/191754/56499809-be69d600-6510-11e9-8eb6-f900d5aec366.png)

The only remaining issue is the "by" in the post metadata (due to mixing RTL and LTR text).

**Comment by alanorth** [comment]
Awesome RTL support added in v1.3.0. Closing issue.

**Comment by sealimousavi** [comment]
Hi, I wanna use this right to left in this theme for farsi lang but I don't know how to do that, may you help me?

**Comment by alanorth** [comment]
@sealimousavi it's easy! I have Farsi on my website with this theme, see here:

https://picturingjordan.com/fa/

The site's Hugo source code is here: https://git.mjanja.ch/alanorth/picturingjordan.com

Check the bottom of the `config.toml` file. My default language is English, which looks for content in files like `blog-post.md`, and then content in other languages like `blog-post.fa.md`.

**Comment by sealimousavi** [comment]
Thanks Alan, I wanna change the default language to farsi and in config.toml I changed the DefaultContentLanguage = "fa" and languageCode = "fa-ir" but still site is in English!

**Comment by sealimousavi** [comment]
And about your blog is your posts in Persian automatically got translated or someone did that? if you want I can help you to translate them and correct them in Grammarly because my native lang is Farsi.

**Comment by sealimousavi** [comment]
I fixed that and now my site is in Persian! Is there any way to change the font? or add a local font?

**Comment by alanorth** [comment]
I'm happy you fixed it. A Persian friend of mine translated my blog posts to Farsi. :)
