### ISSUE TITLE
Make sidebar optional

### ISSUE THREAD

**Issue by alanorth** [alanorth/hugo-theme-bootstrap4-blog#21]
It would be nice to have the sidebar be optional, so users could opt for a single-column site. Right now we can simple not print the sidebar — for example, if a certain config option is present — but the main content doesn't fill the remaining space.

I'm not a Bootstrap expert so I'd need help with this.

**Comment by 0xCLARITY** [comment]
I don't know enough about Hugo themes at the moment to implement this quickly, but what we would want to do is change the class of the `div.blog-main` from `col-sm-8` to `col-sm-10 offset-sm-1` or something similar. We would do this at the same place the config option triggers the sidebar to not display.

**Comment by alanorth** [comment]
Actually, the point of these theme is to bring the [Bootstrap example](https://v4-alpha.getbootstrap.com/examples/blog/) to Hugo—sidebar and all—so I will actually close this issue.
