### ISSUE TITLE
Disable comments on certain sections

### ISSUE THREAD

**Issue by 0xCLARITY** [alanorth/hugo-theme-bootstrap4-blog#30]
It would be useful to disable Disqus comments on certain sections, like disabling comment on "pages" so people cannot comment on an "About Me" page.

**Comment by alanorth** [comment]
You're right, this is desirable. I implemented a quick fix in 61201274fb8a56ac7d1943e992b905100d0531b3 so you can now disable comments in post frontmatter, ie:

```
comments = false
```

Thanks!
