### ISSUE TITLE
Sidebar links don't accept blackfriday setting

### ISSUE THREAD

**Issue by fte378** [alanorth/hugo-theme-bootstrap4-blog#32]
I have

[blackfriday]   
    hrefTargetBlank = true

in my settings to get external links in a new window. The links in the sidebar section don't use this setting.

Regards, Frank

**Comment by alanorth** [comment]
Ah! It's because the sidebar links aren't rendered using Markdown but they should for exactly the reason you said. I tried a quick `markdownify` filter in the sidebar partial but it didn't work. Let me read the docs. 😄

**Comment by alanorth** [comment]
Actually it doesn't seem like this is possible with how we're doing sidebar links right now. We're iterating over a loop of links from the config and printing their properties quite simply in an `<a href=...` tag. To get the behavior you want, the [entire link must be HTML and be processed by the Markdown (blackfriday) processor](https://discuss.gohugo.io/t/how-to-target--blank-in-md/524)...

I could think of a few ways to do this, like with adding an extra property to the links in the config and testing for it before printing the link, but I want to keep things simple.
