### ISSUE TITLE
Menu navbar

### ISSUE THREAD

**Issue by prkpv** [alanorth/hugo-theme-bootstrap4-blog#33]
The theme is very good.
When the "menu navbar" is made up of more than three links and view the mobile, it is a two or three lines, it does not look good. It is possible to make "menu navbar" icon, options config.toml?

**Comment by alanorth** [comment]
Hmm, yes, I see this also happens on mobile on the [Bootstrap v4 blog example](https://v4-alpha.getbootstrap.com/examples/blog/) too. I want to try to avoid adding too many configuration options, and would rather opt for something like a CSS media query that stacks the menu items on mobile (see HTML5 boilerplate [example here](http://hpc.ilri.cgiar.org/mirror/) on mobile).

**Comment by prkpv** [comment]
Yes, it would be good too.

**Comment by alanorth** [comment]
Actually, something like this in Bootstrap v4 should be possible: http://www.codeply.com/view/GVsytKbMkV. I'm not so good in Bootstrap, so I gotta play with it.

**Comment by prkpv** [comment]
This example is ideal.

**Comment by alanorth** [comment]
I haven't forgotten about this. There are lots of changes to navbar behavior in the [latest Bootstrap v4 alpha 6](https://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/) and I'm looking forward to making the navbar stack on small screens.

**Comment by alanorth** [comment]
Ok, the good news is that I kinda got this working using the updated [responsive navbars in Bootstrap v4 Alpha 6](
https://v4-alpha.getbootstrap.com/components/navbar). The bad news is that it requires jQuery, Tether, and Bootstrap JavaScript libraries as well as more from the Bootstrap SCSS (animation) that we are currently not using. This amounts to over 150KiB of extra code, not to mention three extra network requests.

For now, I think it's better if we just give the advice to not add more than ~3 menu items, and in the long term we should use a pure CSS method for stacking the menu items on small screens.
