### ISSUE TITLE
Footer with small content. Discus - Footer.

### ISSUE THREAD

**Issue by prkpv** [alanorth/hugo-theme-bootstrap4-blog#35]
On skrinshetah indicated in red.
![footer](https://cloud.githubusercontent.com/assets/4593735/21642247/e8980ac6-d2bb-11e6-9bf4-3850b80bc7dd.jpeg)
![discus](https://cloud.githubusercontent.com/assets/4593735/21642250/ebdfaf04-d2bb-11e6-9a2a-4d897a03613d.jpeg)

**Comment by prkpv** [comment]
I do not know whether it is correct, the second bug so decided:

single.html
`<article class="blog-post">`
`{ if and (.Site.DisqusShortname) (ne .Params.comments false) }}`
`{{ partial "disqus.html" . }}`
`{{ end }}`
`</article>`

**Comment by alanorth** [comment]
Да, you're right. The padding after the `<article>` was put there before we added comments. I need to move the comments inside the `<article>` and then adjust for semantic HTML5.

**Comment by alanorth** [comment]
I moved the Disqus block into the `<article>` and adjusted the margin in case the sharing icons are hidden. Now it looks much better and should actually be more semantically correct (comments are related to article content and should be inside the article tag, [according to HTML5 specs](https://www.w3.org/TR/html5/sections.html#the-article-element), although we don't have any control over the code Disqus injects). Thanks!
