### ISSUE TITLE
ERROR: 2017/01/05 18:42:46 general.go:236: theme/partials/sidebar.html is an incomplete or empty template 

### ISSUE THREAD

**Issue by dazinator** [alanorth/hugo-theme-bootstrap4-blog#36]
Hello,

I just tried switching my theme from a Lanyon theme to this one.

I installed the theme and set the theme name in my config.yaml.

Howevere when I then build the site I get:

```
ERROR: 2017/01/05 18:42:46 general.go:236: theme/partials/sidebar.html is an incomplete or empty template 
```

Do I need to manually install some partial?

**Comment by dazinator** [comment]
I get the same error message with meta-terms.html.

If I remove this section it goes away:

```
{{ if .Params.categories }}
<i class="fa fa-folder" aria-hidden="true"></i>&nbsp;{{ range $index, $category := .Params.categories }}{{ if gt $index 0 }}, {{ end }}<a href="{{ "/categories/" | relLangURL }}{{ . | urlize }}" rel="category tag">{{ . }}</a>{{ end }}
{{ end }}

```

**Comment by prkpv** [comment]
It is possible that in config.toml something wrong, try config.toml template.
https://github.com/alanorth/hugo-theme-bootstrap4-blog/blob/master/exampleSite/config.toml
There is a description used in a variety of themes More Hugo Quickstart Guide.
https://gohugo.io/overview/quickstart/

**Comment by alanorth** [comment]
Hi, @dazinator. I'm guessing that the categories in your post frontmatter is formatted differently than the theme expects. This is the format that is expected:

```
categories = ["Architecture", "Design"]
```

Because taxonomies are plural—categories, tags—they are always specified with brackets, even if you only have a single term. This seems to be the [format suggested by the Hugo docs]( https://gohugo.io/content/front-matter/). Perhaps I should make a note of it in the README.

**Comment by dazinator** [comment]
Thanks both.
I went through all my categories in my yaml front matter, a few of them looked a bit odd. Changed them all to this format:

```
categories: 
    - "DotNetNuke"
    - "DnnPackager"
```

That seemed to fix the issue with `meta-terms.html.`.

**Comment by alanorth** [comment]
Good to hear, @dazinator. I wonder how your previous theme (Laynon) was handling categories without error.
