### ISSUE TITLE
Disqus didn't show up..

### ISSUE THREAD

**Issue by dazinator** [alanorth/hugo-theme-bootstrap4-blog#37]
After:
1. Setting this as my theme, 
2. Setting `disqusShortName` in my sites `config.yaml` file
3. Setting `comments: true` in my yaml front matter

Disqus was still not visible against my post.

I looked at the `single.html` template which looks like this:

```

{{ if and (.Site.DisqusShortname) (ne .Params.comments false) }}
{{ partial "disqus.html" . }}
{{ end }}

```

I changed that to this and it now works:

```

<!--Disqus-->
  {{if .Params.comments}}
  <div class="container content">
    {{ template "_internal/disqus.html" . }}
  </div>
  {{end}}

```

Wondering why that was necessary!

**Comment by alanorth** [comment]
You only need to add `disqusShortName` to your config and then Disqus will be enabled. There is no need to enable comments on each post. The logic you are looking at is for _disabling_ comments on a per-post basis.

I don't use Disqus, but I just tested locally and it is working.
