### ISSUE TITLE
error in theme/partials/sidebar.html

### ISSUE THREAD

**Issue by cardoe** [alanorth/hugo-theme-bootstrap4-blog#42]
The error I'm receiving is:

ERROR: 2017/01/08 10:33:57 general.go:236: theme/partials/sidebar.html is an incomplete or empty template

The source to the site is: https://github.com/cardoe/cardoe.github.io/tree/content

I wish I knew how to troubleshoot it further but the error message is pretty lacking.

**Comment by alanorth** [comment]
@cardoe, I checked out your source but don't see any content/posts so I can't reproduce the error.

**Comment by cardoe** [comment]
Yeah I haven't actually written anything yet. I did a `huge new post/test.md` and put some ipsum lorem in it. I believe I've figured out how to solve it. I put `[params.sidebar]` under `[params]` in `config.toml` and the error goes away.

**Comment by cardoe** [comment]
Thanks for looking at this @alanorth

**Comment by alanorth** [comment]
Ah, so you didn't have a `[params.sidebar]`. I need to make the template check for it before trying to use it. Thanks for reporting this.

**Comment by alanorth** [comment]
I've added a check to make sure the `[params.sidebar]` block is defined before attempting to use it in the sidebar partial. See: https://github.com/alanorth/hugo-theme-bootstrap4-blog/commit/c9c577178234870f00b98e79dc73dd3f7bc64f58

The theme pretty much needs this to look decent, but we shouldn't error if a user doesn't have it defined. Thanks, @cardoe.

**Comment by cardoe** [comment]
Thanks again @alanorth. I've tested it and verified the fix.
