### ISSUE TITLE
some image not show on static site

### ISSUE THREAD

**Issue by ipoj** [alanorth/hugo-theme-bootstrap4-blog#43]
i am new to hugo and this theme. every thing work fine when i run local server with this command
`$ hugo serve --buildDrafts`
![screen shot 2017-01-11 at 8 20 16 pm](https://cloud.githubusercontent.com/assets/15340333/21850175/db39bb42-d83b-11e6-8b90-83576d19a906.png)

but when i build static site with
`$ hugo --buildDrafts`
static site in public folder, some images(folder icon and social share image) not show. How can i fix this
![screen shot 2017-01-11 at 8 23 01 pm](https://cloud.githubusercontent.com/assets/15340333/21850202/046f8190-d83c-11e6-95cf-60b470e7a0e9.png)

thanks,

**Comment by alanorth** [comment]
Hello. Thanks for using the theme. Are you viewing the static site from `public` or did you upload it to the location specified in `config.toml`, ie for [my site](https://picturingjordan.com):

```
baseurl = "https://picturingjordan.com/"
```

If the icons aren't loading, try checking the browser's developer tools to see if there is an error, and send a screenshot.

**Comment by ipoj** [comment]
yes, i upload it to google appengine. here is  my baseurl
`baseurl = "https://ipojsite.appspot.com/" `
and in developer tools, i get only 404 error of fontawesome-webfont.

**Comment by alanorth** [comment]
Your site otherwise looks fine — i.e. `css/style.css` loads — but the FontAwesome fonts are definitely missing. I think it must be something with your deploy process. I'm not familiar with AppEngine, though.

**Comment by ipoj** [comment]
hi,
i figure it out. it's all about url handlers in appengine config file(app.yaml). thanks, anyway:)
