### ISSUE TITLE
[question] highlight and width of the posts

### ISSUE THREAD

**Issue by dselivanov** [alanorth/hugo-theme-bootstrap4-blog#48]
Thanks for awesome theme. I have 2 questions (sorry if they look obvious, I'm newbie)

1. How to change highlight for source code ? For example [here](https://github.com/digitalcraftsman/hugo-material-docs/blob/27c3ed86650d9e216e6dfd5fe0f6c3c838d70bc4/exampleSite/config.toml) is an example of applying custom `highlight_css` for [hugo-material-docs](https://github.com/digitalcraftsman/hugo-material-docs) theme. 
1. How to change width of the posts? is it possible?

**Comment by fte378** [comment]
Regarding 2:  The CSS includes several fixed width column sizes which are switched when changing  your browser size.
I think they are 730px, 610px, 450px, 330px and 298px.

**Comment by dselivanov** [comment]
@fte378 thanks for answer. Tried to change css in `source/scss` - no effect. Or mb I'm doing totally wrong things. What to change in what file to increase post width? I want to achieve width similar to [this theme](https://github.com/appernetic/hugo-bootstrap-premium/).

**Comment by fte378** [comment]
If you don't generate the theme yourself the file is static/css/style.sss (minified!). Look for media-entries. They are the starting point for sizing.

**Comment by alanorth** [comment]
Thanks for using the theme, @dselivanov!

To use syntax highlighting you need to have Python Pygments installed in your shell environment, and then set the color scheme using the configuration variables described on the [Hugo docs](https://gohugo.io/extras/highlighting/)—it should "just work". I don't use syntax highlighting on my blog, but at least one user is using it (see #39 though).

Changing the width of the posts is beyond the scope of this theme (as I'm only aiming to provide a near perfect copy of the [Bootstrap Blog Template](http://v4-alpha.getbootstrap.com/examples/blog/). But if you want to pursue that you need to override [Bootstrap's breakpoints](https://v4-alpha.getbootstrap.com/layout/overview/) somehow. Refer to the developers section of this theme's readme to see how to compile the SCSS→CSS. I had wanted to allow the sidebar to be optional (see #21) but haven't had time to look at it, and I'm not very good with Bootstrap to be honest.
