### ISSUE TITLE
add appropriate rel's

### ISSUE THREAD

**Issue by xenoterracide** [alanorth/hugo-theme-bootstrap4-blog#51]
would be interesting to add a

```
<link rel="license" href="{{ .Site.License }}"/>
```
to the template

that said, I don't understand why mine isn't rendering :/

https://bitbucket.org/xenoterracide/blog/src/da2beecd30782e7da8970ac5999efc5e1169d0e0/layouts/partial/head-custom.html?at=master&fileviewer=file-view-default

**Comment by alanorth** [comment]
License metadata could be good. Do any robots read `rel="license"`?

I see it's a [W3C recommendation as of 2014](https://www.w3.org/TR/html5/links.html#link-type-license). It's not clear to me, though, how to specify that the license applies to the page content, versus being applied specifically to a hyperlink, image, or HTML5 section... perhaps this should be on the blog post's `<article>` tag?

**Comment by xenoterracide** [comment]
I'm not sure either, I don't know if any specific bots read it... but they could. from reading the html5 spec looks like you can apply it as widely or as granularly as you need it.

**Comment by xenoterracide** [comment]
So looking into the license thing, I've set mine globally in the `head-custom.html` (after fixing my directory to be named appropriately). It seems you can do this globally and search engines might use it. However the spec also advises that you might also set it on more local content (and the nearest element wins?), and I've seen some advice that suggests putting in places like a link in copyright (making me double wonder if perhaps copyright should be a partial). 

So it might be appropriate to have the global license and also allow for a license to be set in individual articles to override for content as needed. I'm not sure what the best way to render this would be.

**Comment by alanorth** [comment]
I'm wary about this licensing microformats stuff—the scope is too big, the specs vary too much in their language ([this one is from 2004!](http://microformats.org/wiki/rel-license)), and I don't see any robots that actually use this. Not to mention, I want to keep the theme as simple as possible without having to worry about many configuration combinations. In the end, there's nothing stopping you from using HTML markup to specify licenses in your Markdown.

Having said that, I am amending my own site's configuration to simply add `rel="license"` to the Creative Commons link in my footer, ala the [Creative Commons usage wiki](https://wiki.creativecommons.org/wiki/Marking_your_work_with_a_CC_license). In `config.toml`:

```
copyright = "[...] content on this site is licensed under a <a rel='license' href='https://creativecommons.org/licenses/by-sa/4.0/'>Creative Commons Attribution 4.0 International license</a>."
```
