### ISSUE TITLE
shortcode not rendering

### ISSUE THREAD

**Issue by xenoterracide** [alanorth/hugo-theme-bootstrap4-blog#52]
sorry this may be a question not a bug, I tried setting copyright to

```
copyright = "Copyright © 2008-{{< year >}} Caleb Cushing. This work is licensed under a [Creative Commons Attribution-NonCommercial 4.0 International License](https://creativecommons.org/licenses/by-nc/4.0/)"
```

but that didn't render https://bitbucket.org/xenoterracide/blog/src/da2beecd30782e7da8970ac5999efc5e1169d0e0/layouts/shortcodes/year.html?at=master&fileviewer=file-view-default

this a template bug? am I doing something wrong?

**Comment by alanorth** [comment]
It looks like you're trying to use Go templating syntax, but only Markdown syntax is supported in the copyright, see [layouts/_default/baseof.html](https://github.com/alanorth/hugo-theme-bootstrap4-blog/blob/master/layouts/_default/baseof.html#L76).

**Comment by xenoterracide** [comment]
yes but, https://gohugo.io/extras/shortcodes#simple-single-word-example-year, I thought you could use those in markdown in hugo? shouldn't this work? couldn't this be made to work?

**Comment by alanorth** [comment]
No, it doesn't seem like it's possible to render Hugo shortcodes when piping to `markdownify` (which is how the copyright text in the footer is rendered). I'm not sure how "normal" post/page Markdown is different.
