### ISSUE TITLE
SHA-256 integrity

### ISSUE THREAD

**Issue by xenoterracide** [alanorth/hugo-theme-bootstrap4-blog#53]
(index):1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://127.0.0.1:1313/css/style.css' with computed SHA-256 integrity 'iWT4FzIzYOMkVgL1RalyTDsQUI3SpoUB85EViSrNwco='. The resource has been blocked.

hmm... maybe a windows build issue? I've only noticed this on localhost, not when it builds in docker and serves from s3...

**Comment by xenoterracide** [comment]
removing integrity works, I think multiple hashes are also possible. Maybe there could just be an if flag in the template. maybe integrity so the logic ends up like 
```
if ! defined integrity { integrity = ... }
```
then all one would have to do is set `HUGO_INTEGRITY=1` (or true or something before running `hugo serve` (at their own risk).

**Comment by alanorth** [comment]
Are you re-compiling the theme's SCSS using `npm run build`?

**Comment by xenoterracide** [comment]
no, I have it [set up as a submodule](https://bitbucket.org/xenoterracide/blog/src/746ea77ead6dda036f907e9cfac0b22a52cc9618/themes/?at=master)

**Comment by alanorth** [comment]
The theme should work out of the box, as I commit the generated hashes to the repository. Where are you seeing this "failed to find a valid digest" message? In the browser's dev tools?

**Comment by xenoterracide** [comment]
correct, again, I'm guessing it might be because git's checkout changed the line endings, which would then change the hash, which would explain why it works fine in production but not locally on the hugo server

**Comment by alanorth** [comment]
Guess it's a problem with Windows... I don't know anything about Windows, sorry. I'm gonna close this now, but perhaps you can try to set up NPM and run `npm run build` in the theme to re-generate the hashes?

**Comment by xenoterracide** [comment]
I would argue whether it's a problem *with* windows (yes M$ thanks for being a dick and using different line endings), or git (thanks git for doing CRLF checkouts, so checkouts will be different per OS, I could change this setting) or an understanding of one way hashes (different content means a different hash). You could also calculate both hashes (I think integrity supports that? it's new to me) by creating a copy of the file and hashing it after replacing `\n` with `\r\n`

for now my workaround (because I'm lazy, too lazy to install Linux on laptop, eventually) is just to remove the integrity from my code when working locally, which is why I suggested a variable to do that. I doubt my running build is better than this... and would require me to install and run things... and would results in files being modified anyways...

**Comment by xenoterracide** [comment]
I can try later to figure out how to get your build to generate both correct hashes, if you'd accept such a patch.

**Comment by hlwjia** [comment]
@xenoterracide which version of Hugo were you using?

I recently encountered the same issue. With a different theme though, so I don't think it's the theme.

https://github.com/adityatelange/hugo-PaperMod/pull/195

As you can read from the above pull request, only sha256 doesn't work. If I use md5 or sha512, they all work perfectly.

I'm starting to suspect it might be one of the Hugo versions is buggy. I use Netlify Hugo 0.77 to build my site. Therefore I don't think it's Windows issue either.

**Comment by xenoterracide** [comment]
I have no idea

**Comment by alanorth** [comment]
Hey, so this is still an issue, eh? If sha512 works then we can use that here. Sounds like a Hugo-on-Windows bug essentially?

**Comment by 8ar10der** [comment]
I found a solution, hope it work for someone.

https://github.com/lxndrblz/anatole/issues/114#issuecomment-828750909

> Hi guys. If you are using your own domain name. I think I may have solved this problem.
> 
> ~Make a long story short, turn off Cloudflare's "Always Use HTTPS" function.~
> Make a long story short, this issue is probably caused by the Cloudflare CDN cache. If you go to the control panel of your Cloudflare and clean your domains cache. The page will be ok.
> 
> I was suffering from this problem for a long time. By checking everyone's solutions, neither my reinstallation of the theme nor changing the git related settings solved the problem.
> 
> So, I shifted my focus. I had always suspected that there was a problem with the resource itself, so if it weren't a problem with it, it could be a problem with the browser fetching the resource. ~Then I thought it might be a problem with HTTPS.~(This is wrong and after much practice I have proven that it is due to Cloudflare's CDN.) So I started checking my settings on Cloudflare, trying to clean the cache. And thus the problem was solved.

**Comment by agarwalarti** [comment]
I am still having this issue, deploying to Github pages. I am not using Cloudflare. So I don't see how this can be a Cloudflare issue.

**Comment by alanorth** [comment]
@agarwalarti are you using my theme? I deploy this theme on one of my blogs in GitHub pages, so it should work. I can't support issues people are having on other themes.
