### ISSUE TITLE
Code in list view is unformatted

### ISSUE THREAD

**Issue by xenoterracide** [alanorth/hugo-theme-bootstrap4-blog#54]
![image](https://cloud.githubusercontent.com/assets/5517/24067779/fc5abe66-0b4e-11e7-975b-aa5487f9df0b.png)
not the greatest looking thing, but looks fine in post
![image](https://cloud.githubusercontent.com/assets/5517/24067783/155ee23e-0b4f-11e7-970d-bad7fd12c179.png)

I'm thinking that there may be a couple of options here.

1. hide code entirely on the front page
2. set fixed width/height so seeing it all would require scrolling

I recall seeing something about default truncating of characters on a the front page, so that might be part of the problem. I don't really need all of the code to display... but it'd be nice for it to be `<pre><code>...` if it does.

**Comment by alanorth** [comment]
We can't tell Hugo to skip `<code>` tags in summary view, unfortunately. I would influencing the summary view by putting a `<!--more-->` tag where you'd like the summary content to end—this is much better than letting Hugo choose the first 100 words or whatever.

See: https://raw.githubusercontent.com/alanorth/picturingjordan.com/master/content/post/dome-of-the-rock.md

The visual appearance of [my blogs](https://picturingjordan.com) using this theme _greatly_ improved when I discovered that trick.

**Comment by xenoterracide** [comment]
is it possible to get hugo to render the code (as code) if it's in the first 100 words? even if it's only part of the code block. But yeah I could definitely use that (probably what I remember seeing) to work around the ugliness.

**Comment by alanorth** [comment]
Unfortunately no, I don't think the theme has any control over how Hugo renders the summary. A theme could probably create/use custom templates with lots of Go template logic or something, but even if it was possible I would avoid it because I want to keep this theme simple for the general use case.
