### ISSUE TITLE
schema.org changes seem to overwrite .Site.Params

### ISSUE THREAD

**Issue by fte378** [alanorth/hugo-theme-bootstrap4-blog#57]
I just noticed that my blog frank.tegtmeyer.net doesn't contain code for the cookie consent anymore.
Also settings like google-site-verification are lost.

The other blog (photoblog.tegtmeyer.net is still fine but is 37 commits behind your latest commit because I didn't update it yet.

Some tests showed that the .Site.Params map doesn't contain all the values from thew config file - only  "author", "description" and "social" (an empty map).
The Params section is completely lost leading to skipping all things dependent on .Site.Param values.

So there is something weird going on.

Regards, Frank

**Comment by alanorth** [comment]
Working here on my local test on git master.
![screen shot 2017-03-29 at 18 09 08-fs8](https://cloud.githubusercontent.com/assets/191754/24461790/f128bf74-14aa-11e7-8628-387b8c054d7d.png)

**Comment by fte378** [comment]
Hm. Then I have to do some more research. I will come back to this when I have more  information.
