### ISSUE TITLE
Option to display full post content in list template

### ISSUE THREAD

**Issue by mikelococo** [alanorth/hugo-theme-bootstrap4-blog#60]
It's nice to have the option to let visitors read content right from the homepage without having to click through a summary. This proposal introduces the optional "truncate" site parameter.

If the truncate parameter is not present or is set to true, posts in the list template are rendered as they have always been, with the "summary" content view.
If the truncate paramter is explicitly set to false, posts in the list template are rendered via a newly introduced "content" content view that displays the full post .Content and does not append a "read more" link.

**Comment by mikelococo** [comment]
Submitted https://github.com/alanorth/hugo-theme-bootstrap4-blog/pull/59, got review feedback. New PR forthcoming.

**Comment by alanorth** [comment]
Resolved in https://github.com/alanorth/hugo-theme-bootstrap4-blog/commit/2e5eef29a67c6d2b0ab4f11aac30a0b3645d4a40. We decided it was tricky and complicated to check the frontmatter's truncate setting, so for now we just support the single site-wide configuration.
