### ISSUE TITLE
Way to modify the font size

### ISSUE THREAD

**Issue by litkhai** [alanorth/hugo-theme-bootstrap4-blog#62]
Hi Alan,
Most conspicuously, I have an application of you to start Hugo with such a nice theme.

In my native language, font size is relatively bigger than that of English. I would like to shrink all of the font size by touching CSS file or so, if possible. 

Can you provide from where I should start?
Please regard me with warm heart that I am a beginner in making a static blog.

Regards,
Kee-Hoon

**Comment by alanorth** [comment]
Hi! Is it Korean? Can you show me a screenshot, I think it's a beautiful script! My own blog is in English and Bulgarian, and the native fonts look pretty good in Bulgarian I think: https://picturingjordan.com/bg/

The font size is set in `source/scss/main.scss` and recompile the CSS using the instructions for developers in the README.

**Comment by alanorth** [comment]
For example, you can change this line in `source/scss/main.scss`:

```css
@media (min-width: 48em) {
  html {
    font-size: 16px;
  }
}
```

And then re-compile the CSS by using `npm run build` in the theme folder (assuming you have NPM and the theme's dependencies installed).

**Comment by litkhai** [comment]
Thank you very much.

I was out of the country for a while. Sorry for late catchup.

Regards,
Kee-Hoon

2017-04-10 17:07 GMT+09:00 Alan Orth <notifications@github.com>:
