### ISSUE TITLE
Menus

### ISSUE THREAD

**Issue by jeprojects** [alanorth/hugo-theme-bootstrap4-blog#69]
Hi,

Are all pages in /content put into the main menu?

I have not set the menu front matter, but it is putting it in the main menu anyway.

**Comment by alanorth** [comment]
Hi! See the comment in [exampleSite/config.toml](https://github.com/alanorth/hugo-theme-bootstrap4-blog/blob/master/exampleSite/config.toml#L62). The default behavior is to add non-post content pages to the navbar menu, but you can change the menu by using a custom navbar.

**Comment by jeprojects** [comment]
Thanks for the info.

I have noticed this is the meta partials:

{{ template "_internal/opengraph.html" . }}
{{ template "_internal/twitter_cards.html" . }}

Do those files exist?

**Comment by alanorth** [comment]
Those are internal partials, they come from Hugo itself.
