### ISSUE TITLE
AMP?

### ISSUE THREAD

**Issue by fte378** [alanorth/hugo-theme-bootstrap4-blog#7]
Not really an issue but more a question.

Would it be hard to make this theme AMP compliant?
I just glanced over the ampproject website and it doesn't look so hard to do.
Images could be a problem and also the generated content itself but else?

What do you think?

Regards, Frank Tegtmeyer

**Comment by alanorth** [comment]
I haven't read much about AMP yet, only some negative things about how you lose a bit of control of your content. See this recent blog post and its discussion on Hacker News:
- https://www.alexkras.com/google-may-be-stealing-your-mobile-traffic/
- https://news.ycombinator.com/item?id=12722590

**Comment by fte378** [comment]
Interesting read. So one could make the site AMP ready and make the head-element which turns on the AMP machinery at the big providers optional.

**Comment by alanorth** [comment]
Frankly I'm not very concerned with AMP right now. This theme is very small and behaves very well by the web standards. My **only** concern is that Google is giving sites that use AMP a boost in their search results.

The vast majority of page size comes from content anyways. Like [your blog](https://photoblog.tegtmeyer.net/) homepage loads 1.9MB, mostly in images — that's a heavy price to pay for mobile users who casually arrive on your homepage. You could limit your homepage to only show ~3 or so posts and then you would see much more improvement in user experience than with AMP (which would surely caution against loading large images as well).

I am a bit annoyed that we have to include the whole of Font Awesome just so we can use ~5 icons (folder, tag, and social icons), so I might look at customizing that in the build process, though.

**Comment by alanorth** [comment]
Ok, on this note, I've reduced the size of the Font Awesome stuff by ~30KiB. If the server hosting the blog supports gzip — as your and my blogs do — the CSS will be compressed and these savings are only about 7KiB. In any case, this is a win for less data transferred over the wire and less memory used on the device when the stylesheet is unzipped. 👍

See: https://github.com/alanorth/hugo-theme-bootstrap4-blog/commit/4d7900457086ef191f26c895f62fff00c2231c99

**Comment by fte378** [comment]
Cool! Thanks.

**Comment by alanorth** [comment]
Eek! More bad things with AMP:

https://shkspr.mobi/blog/2016/11/removing-your-site-from-amp/

Really horrible. Not a fan!

**Comment by fte378** [comment]
Yes, looks bad.
