### ISSUE TITLE
Pretty URL's

### ISSUE THREAD

**Issue by richarvey** [alanorth/hugo-theme-bootstrap4-blog#70]
Is there a way to configure this theme to not add .html to the end of all the post links for example

http://localhost:1313/blog/test.html

a prettier URL would be:

http://localhost:1313/blog/test
or
http://localhost:1313/blog/test/

**Comment by alanorth** [comment]
Hmm, seems like a general Hugo configuration issue. My blog uses this theme and the URLs are "pretty":

- https://picturingjordan.com/2017/06/emperor-hadrians-arch-jerash/

I suspect you need a `[permalinks]` section in your configuration like:

```
[permalinks]                                                                                                                                                                                                                                                                                                                  
  post = "/:year/:month/:slug/"                                                                                                                                                                                                                                                                                               
  page = "/:slug/"
```
