### ISSUE TITLE
Add proper 404 page

### ISSUE THREAD

**Issue by gemmell** [alanorth/hugo-theme-bootstrap4-blog#72]
Add a 404 page to this template.

**Comment by alanorth** [comment]
It's kinda server specific to do this (ie `ErrorDocument` or `error_page` in Apache and nginx). But anyways, there could be a simple template in the bootstrap-blog style I guess...

**Comment by alanorth** [comment]
I added a minimal HTTP 404 page. You still need to configure your web server to use it though. Thanks for the idea @gemmell.
