### ISSUE TITLE
Responsive Navigation

### ISSUE THREAD

**Issue by Doocey** [alanorth/hugo-theme-bootstrap4-blog#73]
If I'm not mistaken, it looks like there's no responsive nav on mobile devices? Should be fairly straight forward to implement with **navbar** given it uses Bootstrap I would think? Thanks.

**Comment by alanorth** [comment]
Hi! Yeah the navbar doesn't look great on mobile. Primarily I try to stay true to the [Bootstrap Blog Example](http://getbootstrap.com/docs/4.0/examples/blog/) theme from the Bootstrap documentation, but I did play with enabling the responsive navbar in #33. Eventually I decided against it, as I'm currently using only the grid functionality from Bootstrap:

> [...] it requires jQuery, Tether, and Bootstrap JavaScript libraries as well as more from the Bootstrap SCSS (animation) that we are currently not using. This amounts to over 150KiB of extra code, not to mention three extra network requests.

What do you think?

**Comment by Doocey** [comment]
Aha, that makes sense! Not worth it given its costliness!
