### ISSUE TITLE
Invalid link in ReadME

### ISSUE THREAD

**Issue by JOduMonT** [alanorth/hugo-theme-bootstrap4-blog#77]
Hi Alan;

in the ReadME of this theme you point to : https://github.com/gohugoio/hugo/blob/master/docs/content/content/multilingual.md which is a dead link

I did'nt the multilingual.md page.

May I suggest to point this link at : https://github.com/gohugoio/hugo/tree/master/examples/multilingual

**Comment by alanorth** [comment]
Yes you're right. It seems they did a major documentation rework a few months ago and stuff got shifted around. I'll update the link to here:

https://gohugo.io/content-management/multilingual
