### ISSUE TITLE
Is there a way to control the order of links in the navbar?

### ISSUE THREAD

**Issue by joeharrison714** [alanorth/hugo-theme-bootstrap4-blog#78]
Navbar links appear to be alphabetical, no matter the order in config. Is there any way to control that?

**Comment by alanorth** [comment]
If you check the comments in [exampleConfig/config.toml](https://github.com/alanorth/hugo-theme-bootstrap4-blog/blob/master/exampleSite/config.toml) you will see a setting for `custom_navbar`. Once you're using a custom navbar you should be able to use standard Hugo parameters like "weight" to order the links. See: https://gohugo.io/content-management/menus/
