### ISSUE TITLE
lang attribute of html tag not set

### ISSUE THREAD

**Issue by fte378** [alanorth/hugo-theme-bootstrap4-blog#86]
I just noticed that the lang attribute in my blog was set to "en".
I have set

languageCode = "de"
defaultContentLanguage = "de"

in config.toml.

After changing .Lang in baseof.html to .Site.Language.Lang the language was correctly set to "de".

**Comment by alanorth** [comment]
Hmm. Must be some subtle configuration issue. I have this post in English and Bulgarian and the HTML lang attribute is set correctly to `en` and `bg` on each:

- https://picturingjordan.com/2016/12/grandeur-petra/
- https://picturingjordan.com/bg/2017/01/grandeur-petra/

I have the following language attributes in `config.toml`:

```
languageCode = "en-us"
DefaultContentLanguage = "en" 

# Languages to render
[languages.en]
[languages.bg]
  date_format = "02 Jan 2006"
```
