### ISSUE TITLE
More Sharing Links/Icons

### ISSUE THREAD

**Issue by chris-short** [alanorth/hugo-theme-bootstrap4-blog#87]
I'd like to be able to add Share buttons for numerous sites (StumbleUpon, Reddit, HN, etc.). As I'm not a frontend dev re-compiling scss or using node to rebuild a theme is a foreign concept to me. Can we lower the barrier to entry here?

**Comment by alanorth** [comment]
Hi! I completely understand. I've added StumbleUpon, Reddit, and Hacker News (see https://github.com/alanorth/hugo-theme-bootstrap4-blog/commit/f54541e87af55a2c16d77a18587b1c72678cf72a). Any others you'd like? Feel free to close if you're happy.
