### ISSUE TITLE
No Styling

### ISSUE THREAD

**Issue by DigiJo** [alanorth/hugo-theme-bootstrap4-blog#90]
Hi

I am new to Hugo. When installing the theme and deploying it to localhost:1313, the website is not generating the css. Any ideas why?

https://github.com/seojoe/digijo/tree/master/themes/hugo-theme-bootstrap4-blog

**Comment by alanorth** [comment]
Hi, your repository is only the theme, not an actual Hugo blog. You need to create a new blog and then configure it to use this theme.

- See my blog's code here: https://github.com/alanorth/picturingjordan.com
- See the Hugo quickstart: https://gohugo.io/getting-started/quick-start
