### ISSUE TITLE
Update to Bootstrap v4.1.1

### ISSUE THREAD

**Issue by coliff** [alanorth/hugo-theme-bootstrap4-blog#98]

**Comment by alanorth** [comment]
Hi @coliff. I updated to Bootstrap v4.1.1 two months ago in commit 36c77a90fd09dabfad1f08d3ad709134d6076f8f.

**Comment by coliff** [comment]
Hi there, Sorry - I didn't realise I had opened an issue about this before... I saw that Bootstrap 4.1.0 is used here:
https://github.com/alanorth/hugo-theme-bootstrap4-blog/blob/master/static/css/style.css

**Comment by alanorth** [comment]
Hey you're right. I regenerated the static assets but it looks like they didn't get updated judging from the version number. Well anyways, I just saw [Bootstrap v4.1.2 was released](https://blog.getbootstrap.com/2018/07/12/bootstrap-4-1-2/) so I will take a look at that closer now!

**Comment by alanorth** [comment]
By the way, @coliff, I found my error regarding to the mysterious "old" version: I had simply forgotten to copy the version number comment in the `bootstrap.scss` file. Ciao!
